version: "3.9"
services:
 app:
   build: .
   networks:
     - main
   env_file:
     - '.env'
   depends_on:
     - db
   ports:
     - "8000:8000"
   volumes:
     - ./:/app
 db:
   image: postgres:14
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   env_file:
     - '.env'
   networks:
     - main
   restart: unless-stopped
 nginx:
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./static:/app/static
   ports:
     - "80:80"
   networks:
     - main
   depends_on:
     - app

networks:
 main:

volumes:
  postgres_data: